# Generated by Django 4.0.7 on 2023-03-04 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Name must be greater than 1 character')])),
            ],
        ),
    ]
