# Generated by Django 4.0.7 on 2023-06-27 12:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpt_place', models.CharField(max_length=30)),
                ('gpt_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Duration must be greater than 1 character')])),
                ('gpt_result', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpt_place', models.CharField(max_length=30)),
                ('gpt_result', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Duration must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_place', models.CharField(max_length=30)),
                ('stat_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Duration must be greater than 1 character')])),
                ('stat_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Duration must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='Search_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_place', models.CharField(max_length=30)),
                ('search_duration', models.IntegerField()),
                ('search_query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
