# Generated by Django 4.0.7 on 2023-08-25 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('gpt_place', models.CharField(max_length=30)),
                ('gpt_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Duration must be greater than 1 day')])),
                ('gpt_result', models.TextField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('food_place', models.CharField(max_length=30)),
                ('food_result', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalisedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_itinerary_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('p_gpt_place', models.CharField(max_length=30)),
                ('p_gpt_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Duration must be greater than 1 day')])),
                ('p_gpt_result', models.TextField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Duration must be greater than 1 character')])),
            ],
        ),
    ]
