# Generated by Django 4.0.7 on 2023-03-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='duration',
            new_name='Mduration',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='place',
            new_name='Mplace',
        ),
        migrations.AddField(
            model_name='queries',
            name='Mresult',
            field=models.TextField(default='this is a test', max_length=10000),
            preserve_default=False,
        ),
    ]
