# Generated by Django 4.0.7 on 2023-08-29 15:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaliseddata',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='queries',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Duration must be greater than 1 day'), django.core.validators.MaxValueValidator(10, 'Duration must be less than 10 days')]),
        ),
    ]
