# Generated by Django 4.0.7 on 2023-06-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_search_history_test_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_history',
            name='test_text',
        ),
    ]
