# Generated by Django 4.0.7 on 2023-03-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_rename_duration_queries_mduration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='Mresult',
        ),
    ]
