# Generated by Django 4.0.7 on 2023-03-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0003_remove_queries_mresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='Mduration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='queries',
            old_name='Mplace',
            new_name='place',
        ),
    ]
