# Generated by Django 4.0.7 on 2023-03-05 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_rename_mduration_queries_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpt_place', models.CharField(max_length=30)),
                ('gpt_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Name must be greater than 1 character')])),
                ('gpt_result', models.TextField(max_length=10000)),
            ],
        ),
    ]
