# Generated by Django 4.0.7 on 2023-03-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0006_alter_data_gpt_duration_alter_queries_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpt_place', models.CharField(max_length=30)),
                ('gpt_result', models.TextField(max_length=10000)),
            ],
        ),
    ]
