# Generated by Django 4.0.7 on 2023-03-18 06:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askme', '0007_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_place', models.CharField(max_length=30)),
                ('stat_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Duration must be greater than 1 character')])),
                ('stat_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Duration must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_place', models.CharField(max_length=30)),
                ('search_duration', models.IntegerField()),
                ('search_query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
